{
 "title": "ALL Pods Status",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace =~ \"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", namespace=~\"$namespace\", phase=\"Running\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pod Count - Not Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", namespace=~\"$namespace\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", namespace=~\"$namespace\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", namespace=~\"$namespace\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", namespace=~\"$namespace\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\"}[2m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "Mem Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "Mem Limit"
    },
    {
     "expr": "sum(sum(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\"} / (1024 * 1024 * 1024)) by (pod))",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"POD\"} / (1024 * 1024)) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\"}) / (1024 * 1024)",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "sum(container_fs_limit_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\"}) / (1024 * 1024)",
     "legendFormat": "Disk Limit"
    }
   ]
  },
  {
   "title": "Disk I/O Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}) / (1024 * 1024)",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "sum(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}) / (1024 * 1024)",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "Network I/O Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[2m])) / (1024 * 1024)",
     "legendFormat": "Network In"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\"}[2m])) / (1024 * 1024)",
     "legendFormat": "Network Out"
    }
   ]
  }
 ]
}