{
 "title": "Betatest Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "컨테이너 Throttle 된 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "컨테이너 Throttle 된 기간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total[5m])"
    }
   ]
  },
  {
   "title": "api 서버가 거절된 횟수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(apiserver_audit_requests_rejected_total[5m])"
    }
   ]
  },
  {
   "title": "HTTP 요청 API 서버 오류 탐지 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total{code=~\"5.*\"}[10m]))"
    }
   ]
  },
  {
   "title": "CPU 사용량 (KB) , 메모리 사용량 (GB) (일별)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_cpu_user_seconds_total)/1024"
    },
    {
     "expr": "sum(container_memory_usage_bytes)/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Waiting Pod, reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "waitingpod"
    },
    {
     "expr": "kube_pod_container_status_waiting_reason"
    }
   ]
  },
  {
   "title": "컨테이너 네트워크 수신 (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m])) by (kubernetes_io_hostname) /1024",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "컨테이너 별 네트쿼트 송신량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m])) by (kubernetes_io_hostname) /1024",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  }
 ]
}