{
 "title": "Worker node status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "컨테이너 네트워크 총송수신(MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[2m]))/(1024 * 1024)",
     "legendFormat": "Network In"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[2m])) / (1024 * 1024)",
     "legendFormat": "Network Out"
    }
   ]
  },
  {
   "title": "Number of Worker node ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Workernode load AVG (1min,5m, 15m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"66.4.133.196:9100\"}) / count(node_cpu_seconds_total{mode=\"system\", instance=\"66.4.133.196:9100\"})",
     "legendFormat": "node load 1min"
    },
    {
     "expr": "sum(node_load5{instance=\"66.4.133.196:9100\"}) / count(node_cpu_seconds_total{mode=\"system\", instance=\"66.4.133.196:9100\"})",
     "legendFormat": "node load 5min"
    },
    {
     "expr": "sum(node_load15{instance=\"66.4.133.196:9100\"}) / count(node_cpu_seconds_total{mode=\"system\", instance=\"66.4.133.196:9100\"})",
     "legendFormat": "node load 15min"
    }
   ]
  }
 ]
}